name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Create google-services.json file
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Check lint
        run: ./gradlew :app:lintProdDebug
      - name: Check binary compatibility
        run: ./gradlew :lib:checkLegacyAbi
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*'
          if-no-files-found: warn

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Create google-services.json file
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Run tests
        run: ./gradlew :app:testProdDebugUnitTest :lib:test
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: '**/build/reports/tests/'
          if-no-files-found: warn

  build-verification:
    name: Build Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Create google-services.json file
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Assemble Debug
        run: ./gradlew :app:assembleProdDebug
