name: Deploy Internal

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_internal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/gradle-build-action@v3
      id: setup-gradle
      with:
        gradle-version: release-candidate

    - name: Setup Ruby (for Fastlane)
      uses: ruby/setup-ruby@v1.171.0
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install Fastlane
      run: bundle install

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Decode Secrets
    - name: Decode Keystore for prod signing
      run: |
        echo "$KEYSTORE_PROD" > app/keystore.jks.base64
        base64 -d -i app/keystore.jks.base64 > app/keystore.jks
      env:
        KEYSTORE_PROD: ${{ secrets.KEYSTORE_PROD }}

    - name: Decode Firebase App Distribution JSON file
      run: |
        echo "$KEYSTORE_PROD" > app/keystore.jks.base64
        base64 -d -i app/keystore.jks.base64 > app/keystore.jks
        echo "$GOOGLE_PLAY_DISTRIBUTION_JSON" > app/google-play-distribution.json.base64
        base64 -d -i app/google-play-distribution.json.base64 > app/google-play-distribution.json
        echo "$GOOGLE_SERVICES_JSON" > app/google-services.json.base64
        base64 -d -i app/google-services.json.base64 > app/google-services.json
      env:
        KEYSTORE_PROD: ${{ secrets.KEYSTORE_PROD }}
        GOOGLE_PLAY_DISTRIBUTION_JSON: ${{ secrets.GOOGLE_PLAY_DISTRIBUTION_JSON }}
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    - name: Build App Bundle and deploy to Google Play Internal Testing
      run: bundle exec fastlane deploy_google_play_internal
      env:
        SIGNING_KEYSTORE: ${{ github.workspace }}/app/keystore.jks
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
